# Generated by Django 5.2.6 on 2025-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('reading', 'Currently Reading'), ('read', 'Read')], default='want_to_read', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Rate 1-5 stars', null=True)),
                ('review', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
